# Generated by Django 5.1.6 on 2025-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prise",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
