# Generated by Django 5.1.6 on 2025-04-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_course_prise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="prise",
            new_name="price",
        ),
    ]
