# Generated by Django 5.1.6 on 2025-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_rename_prise_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
    ]
