# Generated by Django 5.1.6 on 2025-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_stripe_product_id_lesson_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена урока"
            ),
        ),
    ]
