# Generated by Django 5.1.6 on 2025-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
